# NumPy Assignement

1. What is a Python library? Why do we use Python libraries?

2. What is the ^ifference between Numpy array an^ List?

3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [7]:
import numpy as np
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
x = arr.shape
y = arr.size
z = arr.ndim
print("Shape is {}\nSize is {}\nDimension is {}".format(x,y,z))

Shape is (3, 4)
Size is 12
Dimension is 2


4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [11]:
arr[0:1]

array([[1, 2, 3, 4]])

5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [12]:
arr[2,3]

12

6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [15]:
arr[:,1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [21]:
np.random.randn(3,3)

array([[-0.22428067,  1.19253804,  1.1217484 ],
       [-1.93602171, -0.62548931, -1.17594793],
       [-0.09472456, -2.11248078, -0.47733698]])

8. Describe the difference between np.random.rand and np.random.randn?

np.random.rand

==>Generates random numbers from a uniform distribution over [0, 1)

==>Suitable for cases where you need uniformly distributed values within a specified range

==>Values are all non-negative and less than 1

np.random.randn

==>Generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).

==>Suitable for cases where you need normally distributed values.

==>Values can be positive or negative and are centered around 0.

9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [24]:
np.expand_dims(arr, axis=0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [26]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [27]:
np.transpose(arr)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

11. Consider the following matrix:

Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python

1 Index wise multiplication

2 Matrix multiplication

3 Add both the matrices

4 Substract matrix B from A

5 Divide Matrix B by A

In [75]:
A = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

1. Index wise multiplication

In [76]:
A * B

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [77]:
np.multiply(A, B)

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

2. Matrix multiplication

In [79]:
np.dot(A,B)
A @ B
np.matmul(A,B)

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

3. Add both the matrices

In [49]:
A + B

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

4. Substract matrix B from A

In [50]:
A - B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

5. Divide Matrix B by A

In [52]:
B / A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

12.  Which function in Numpy can be used to swap the byte order of an array?

numpy.ndarray.byteswap()

In [53]:
arr.byteswap()

array([[ 16777216,  33554432,  50331648,  67108864],
       [ 83886080, 100663296, 117440512, 134217728],
       [150994944, 167772160, 184549376, 201326592]])

13.  What is the significance of the np.linalg.inv function?

The np.linalg.inv function is a fundamental tool in numerical linear algebra, providing a way to compute the inverse of a matrix, which is essential for many theoretical and practical applications.

In [55]:
np.linalg.inv(np.array([[1,2],[3,4]]))

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

14. What does the np.reshape function do, and how is it used?

 Reshape Function in NumPy is used to change the shape of an existing array without changing its data.

In [62]:
arr.reshape(4,3)
arr.reshape(6,2)
arr.reshape(2,6)
arr.reshape(12,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

15. What is broadcasting in Numpy?

Broadcasting is a feature that allows NumPy to perform arithmetic operations on arrays of different shapes efficiently. It follows specific rules to align the shapes, making it possible to perform operations without explicitly reshaping or replicating the data. This leads to more efficient and concise code, making NumPy a powerful tool for numerical and scientific computing.

In [64]:
A = np.array([[1], [2], [3]])
B = np.array([10, 20, 30])
A + B

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [63]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[1],
              [2]])
A * B

array([[ 1,  2,  3],
       [ 8, 10, 12]])